# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_popup', models.BooleanField(default=False, verbose_name='是否弹窗强提醒')),
                ('start_time', models.DateTimeField(verbose_name='展示开始时间')),
                ('end_time', models.DateTimeField(verbose_name='展示结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'db_table': 'operations_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='图片地址')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='跳转链接')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('position', models.CharField(choices=[('home_top', '首页顶部'), ('course_list_top', '课程列表顶部')], default='home_top', max_length=50, verbose_name='位置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'operations_banners',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='统计日期')),
                ('new_users', models.IntegerField(default=0, verbose_name='新增用户数')),
                ('active_users', models.IntegerField(default=0, verbose_name='活跃用户数')),
                ('new_courses', models.IntegerField(default=0, verbose_name='新增课程数')),
                ('total_enrollments', models.IntegerField(default=0, verbose_name='累计选课人次')),
                ('new_enrollments', models.IntegerField(default=0, verbose_name='当日选课人次')),
                ('certificates_issued', models.IntegerField(default=0, verbose_name='颁发证书数')),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='当日营收')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'db_table': 'operations_daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='举报对象ID')),
                ('reason', models.CharField(max_length=200, verbose_name='举报原因')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('content_snapshot', models.JSONField(blank=True, help_text='防止用户删除/修改证据', null=True, verbose_name='被举报内容快照')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('admin_remark', models.TextField(blank=True, null=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='举报对象类型')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
                'db_table': 'operations_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
