# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '学习中'), ('completed', '已完成'), ('dropped', '已退课')], default='active', max_length=20, verbose_name='状态')),
                ('progress', models.FloatField(default=0.0, help_text='0-100的百分比', verbose_name='学习进度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='StudentKnowledgeMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.FloatField(default=0.0, help_text='0.0-1.0之间，算法：得分/总分', verbose_name='掌握度')),
                ('total_attempts', models.IntegerField(default=0, help_text='作业/考试/测验总次数', verbose_name='练习总次数')),
                ('total_score_earned', models.FloatField(default=0.0, verbose_name='实际得分总和')),
                ('total_score_possible', models.FloatField(default=0.0, verbose_name='总分值')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生知识掌握度',
                'verbose_name_plural': '学生知识掌握度',
                'db_table': 'student_knowledge_masteries',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=50, unique=True, verbose_name='证书编号')),
                ('file', models.FileField(blank=True, help_text='生成的PDF/Image', null=True, upload_to='certificates/%Y/%m/', verbose_name='证书文件')),
                ('template_url', models.URLField(blank=True, null=True, verbose_name='证书模板快照')),
                ('meta_snapshot', models.JSONField(blank=True, help_text='课程名、讲师、学期名等，防止源数据变更', null=True, verbose_name='元数据快照')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='最终成绩')),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已撤销'), ('expired', '已过期')], default='active', max_length=20, verbose_name='状态')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='颁发时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
                'db_table': 'certificates',
            },
        ),
    ]
