# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('knowledge', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='courses.courseterm', verbose_name='关联班期'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.classgroup', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courseterm', verbose_name='关联班期'),
        ),
        migrations.AddField(
            model_name='studentknowledgemastery',
            name='knowledge_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_masteries', to='knowledge.knowledgepoint', verbose_name='知识点'),
        ),
        migrations.AddField(
            model_name='studentknowledgemastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_masteries', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_no'], name='idx_cert_no'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student', 'status'], name='idx_cert_student'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='idx_enroll_status'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'term')},
        ),
        migrations.AddIndex(
            model_name='studentknowledgemastery',
            index=models.Index(fields=['student', 'mastery_level'], name='idx_mastery_level'),
        ),
        migrations.AlterUniqueTogether(
            name='studentknowledgemastery',
            unique_together={('student', 'knowledge_point')},
        ),
    ]
