# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_snapshot', models.JSONField(help_text='存储答题时的题目内容', verbose_name='题目快照')),
                ('answer_content', models.TextField(verbose_name='学生答案')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
            ],
            options={
                'verbose_name': '答题详情',
                'verbose_name_plural': '答题详情',
                'db_table': 'exam_answers',
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, help_text='题目ID: 答案内容', null=True, verbose_name='考生答卷数据')),
                ('total_score', models.IntegerField(blank=True, null=True, verbose_name='总分')),
                ('status', models.CharField(choices=[('ongoing', '考试中'), ('submitted', '已提交'), ('grading', '阅卷中'), ('graded', '已阅卷')], default='ongoing', max_length=20, verbose_name='状态')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='评语')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='阅卷时间')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'db_table': 'exam_submissions',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='后台管理检索用', max_length=200, verbose_name='题目名称')),
                ('type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('true_false', '判断题'), ('fill', '填空题'), ('essay', '简答题')], max_length=20, verbose_name='题目类型')),
                ('content', models.JSONField(help_text='题干、选项、答案、解析', verbose_name='题目完整内容')),
                ('grading_rule', models.JSONField(blank=True, help_text='{"fuzzy_match": true, "ignore_case": true}', null=True, verbose_name='自动批改规则')),
                ('difficulty', models.FloatField(default=0.5, help_text='0.1-1.0，用于贪心算法适配度参数', verbose_name='难度系数')),
                ('score', models.IntegerField(default=5, verbose_name='题目分值')),
                ('is_active', models.BooleanField(default=True, help_text='软删除', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'db_table': 'question_bank',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='试卷标题')),
                ('total_score', models.IntegerField(default=100, verbose_name='总分')),
                ('duration', models.IntegerField(default=90, verbose_name='考试时长(分钟)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '试卷模板',
                'verbose_name_plural': '试卷模板',
                'db_table': 'exam_papers',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('questions_snapshot', models.JSONField(blank=True, help_text='考试发布时固化题目内容', null=True, verbose_name='题目快照')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='courses.classgroup', verbose_name='关联班级')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exampaper', verbose_name='关联试卷')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='courses.courseterm', verbose_name='关联班期')),
            ],
            options={
                'verbose_name': '考试场次',
                'verbose_name_plural': '考试场次',
                'db_table': 'exam_sessions',
            },
        ),
    ]
