# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exams', to=settings.AUTH_USER_MODEL, verbose_name='阅卷人'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.examsession', verbose_name='关联场次'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_details', to='exams.examsubmission', verbose_name='关联考试记录'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='出题人'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='knowledge_points',
            field=models.ManyToManyField(blank=True, related_name='questions', to='knowledge.knowledgepoint', verbose_name='关联知识点'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='questions',
            field=models.ManyToManyField(help_text='用于组卷编辑', related_name='exam_papers', to='exams.questionbank', verbose_name='关联题目'),
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['type', 'is_active'], name='idx_question_type'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['difficulty'], name='idx_question_diff'),
        ),
    ]
