# Generated by Django 5.1.6 on 2026-02-15 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseterm_status'),
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='class_group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='courses.classgroup', verbose_name='关联班级'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='feedback',
            field=models.TextField(blank=True, default='', verbose_name='评语'),
            preserve_default=False,
        ),
    ]
