# Generated by Django 5.1.6 on 2026-02-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseterm_status'),
        ('exams', '0003_alter_examsession_class_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='grading_rule',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='knowledge_points',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='score',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course', verbose_name='所属课程'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='title',
            field=models.CharField(help_text='后台管理检索用，不展示给学生', max_length=200, verbose_name='题目名称'),
        ),
    ]
