# Generated by Django 5.1.6 on 2026-02-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_questionbank_grading_rule_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='questionbank',
            name='idx_question_type',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='is_active',
        ),
    ]
