# Generated by Django 5.1.6 on 2026-02-24 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseterm_status'),
        ('exams', '0005_remove_questionbank_idx_question_type_and_more'),
        ('knowledge', '0004_questioncategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='category',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge.questioncategory', verbose_name='所属文件夹'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除', verbose_name='是否启用'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['type', 'is_deleted'], name='idx_question_type'),
        ),
    ]
