# Generated by Django 5.1.6 on 2026-02-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_questionbank_category_questionbank_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除', verbose_name='是否已删除'),
        ),
    ]
