# Generated by Django 5.1.6 on 2026-02-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_questionbank_is_deleted'),
        ('knowledge', '0004_questioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge.questioncategory', verbose_name='所属文件夹'),
        ),
    ]
