# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(blank=True, help_text='仅存答案，不含题目', null=True, verbose_name='提交内容')),
                ('files', models.JSONField(blank=True, help_text='存储文件URL列表', null=True, verbose_name='附件')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('graded', '已批改')], default='draft', max_length=20, verbose_name='状态')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='评语')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='批改时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'db_table': 'homework_submissions',
            },
        ),
        migrations.CreateModel(
            name='HomeworkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='作业内容/要求')),
                ('total_score', models.IntegerField(default=100, verbose_name='总分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作业模板',
                'verbose_name_plural': '作业模板',
                'db_table': 'homework_templates',
            },
        ),
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='发布时固化模板标题', max_length=200, verbose_name='作业标题')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('content_snapshot', models.JSONField(blank=True, help_text='包含题目、分值、标准答案', null=True, verbose_name='作业完整快照')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('class_group', models.ForeignKey(blank=True, help_text='为空则发给全班期', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_assignments', to='courses.classgroup', verbose_name='指定班级')),
            ],
            options={
                'verbose_name': '作业发布',
                'verbose_name_plural': '作业发布',
                'db_table': 'homework_assignments',
            },
        ),
    ]
