# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('exams', '0002_initial'),
        ('homework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkassignment',
            name='specific_students',
            field=models.ManyToManyField(blank=True, help_text='例外/补考', related_name='specific_homework_assignments', to=settings.AUTH_USER_MODEL, verbose_name='指定学生'),
        ),
        migrations.AddField(
            model_name='homeworkassignment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='courses.courseterm', verbose_name='关联班期'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homeworkassignment', verbose_name='关联发布记录'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='homeworktemplate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_templates', to='courses.course', verbose_name='所属课程'),
        ),
        migrations.AddField(
            model_name='homeworktemplate',
            name='questions',
            field=models.ManyToManyField(blank=True, help_text='用于客观题自动批改', related_name='homework_templates', to='exams.questionbank', verbose_name='关联题目'),
        ),
        migrations.AddField(
            model_name='homeworkassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='homework.homeworktemplate', verbose_name='关联作业模板'),
        ),
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
