# Generated by Django 5.1.6 on 2026-02-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkassignment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='homework.homeworktemplate', verbose_name='关联作业模板'),
        ),
    ]
