# Generated by Django 5.1.6 on 2026-02-15 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseterm_status'),
        ('homework', '0003_alter_homeworkassignment_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkassignment',
            name='class_group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='courses.classgroup', verbose_name='指定班级'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='feedback',
            field=models.TextField(blank=True, default='', verbose_name='评语'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='files',
            field=models.JSONField(blank=True, default=list, help_text='存储文件URL列表', null=True, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('pending', '未提交'), ('submitted', '已提交'), ('graded', '已批改')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='homeworktemplate',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='作业内容/要求'),
            preserve_default=False,
        ),
    ]
