# Generated by Django 5.1.6 on 2026-02-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='verified_at',
        ),
    ]
