# Generated by Django 5.1.6 on 2026-02-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_phone',
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='未知', max_length=50, verbose_name='真实姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
