# Generated by Django 5.1.6 on 2025-04-26 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lerning_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, help_text='是否完成', verbose_name='是否完成')),
                ('last_visited', models.DurationField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='上次观看时长')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
                'db_table': 'learning_progress',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('course', '课程'), ('chapter', '章'), ('section', '节'), ('subsection', '小节')], help_text='节点类型', max_length=20, verbose_name='节点类型')),
                ('title', models.CharField(help_text='课程名称', max_length=200, verbose_name='课程名称')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField(help_text='课程描述')),
                ('tags', models.TextField(help_text='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
                'db_table': 'Node',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NodeClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='section_content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.TextField(blank=True, help_text='文本内容', null=True, verbose_name='文本内容')),
                ('file_url', models.FileField(blank=True, null=True, upload_to='chapters_file/', verbose_name='文件路径')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='chapters_images/', verbose_name='图片路径')),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '章节小节',
                'verbose_name_plural': '章节小节',
                'db_table': 'section_contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='video_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='chapters_videos/', verbose_name='视频路径')),
                ('total_duration', models.DurationField(help_text='时长', validators=[django.core.validators.MinValueValidator(0)], verbose_name='视频总时长')),
                ('resolution', models.CharField(choices=[('1080p', '1920x1080'), ('720p', '1280x720'), ('480p', '854x480')], default='1080p', help_text='分辨率', max_length=20, verbose_name='视频分辨率')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='视频大小')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '视频内容',
                'db_table': 'video_contents',
            },
        ),
    ]
