# Generated by Django 5.1.6 on 2025-04-26 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lerning_progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='author',
            field=models.ForeignKey(help_text='作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.node', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='lerning_progress',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.node'),
        ),
        migrations.AddField(
            model_name='nodeclosure',
            name='ancestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='courses.node'),
        ),
        migrations.AddField(
            model_name='nodeclosure',
            name='descendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='courses.node'),
        ),
        migrations.AddField(
            model_name='section_content',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.node'),
        ),
        migrations.AddField(
            model_name='video_content',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.node'),
        ),
        migrations.AddIndex(
            model_name='lerning_progress',
            index=models.Index(fields=['last_visited'], name='learning_pr_last_vi_8d7811_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeclosure',
            unique_together={('ancestor', 'descendant')},
        ),
        migrations.AddConstraint(
            model_name='section_content',
            constraint=models.UniqueConstraint(fields=('node', 'order'), name='unique_order_in_node'),
        ),
        migrations.AddIndex(
            model_name='video_content',
            index=models.Index(fields=['resolution'], name='video_conte_resolut_fef7d3_idx'),
        ),
    ]
