# Generated by Django 5.1.6 on 2025-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, help_text='描述', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='node',
            name='tags',
            field=models.TextField(blank=True, help_text='标签', null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.CharField(help_text='标题', max_length=200, verbose_name='标题'),
        ),
    ]
