# Generated by Django 5.1.6 on 2025-04-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_node_description_alter_node_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section_content',
            options={'ordering': ['order'], 'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
    ]
