# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如 循环结构', max_length=100, verbose_name='知识点名称')),
                ('object_id', models.PositiveIntegerField(verbose_name='关联对象ID')),
                ('content_type', models.ForeignKey(help_text='仅限 Course, Lesson, QuestionBank', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联类型')),
                ('parent', models.ForeignKey(blank=True, help_text='支持树状结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.knowledgepoint', verbose_name='父知识点')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'db_table': 'knowledge_points',
                'indexes': [models.Index(fields=['parent'], name='idx_kp_parent'), models.Index(fields=['content_type', 'object_id'], name='idx_kp_content')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如 Python, 难度:高', max_length=50, unique=True, verbose_name='标签名称')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_tag_content'), models.Index(fields=['name'], name='idx_tag_name')],
            },
        ),
    ]
