# Generated by Django 5.1.6 on 2026-02-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePointRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='知识点关联对象ID')),
            ],
            options={
                'verbose_name': '知识点挂载',
                'db_table': 'knowledge_point_rels',
            },
        ),
        migrations.CreateModel(
            name='TagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='标签关联对象ID')),
            ],
            options={
                'verbose_name': '标签关联',
                'db_table': 'tag_relations',
            },
        ),
        migrations.AlterModelOptions(
            name='knowledgepoint',
            options={'ordering': ['order', 'id'], 'verbose_name': '知识点', 'verbose_name_plural': '知识点'},
        ),
        migrations.RemoveIndex(
            model_name='knowledgepoint',
            name='idx_kp_parent',
        ),
        migrations.RemoveIndex(
            model_name='knowledgepoint',
            name='idx_kp_content',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='idx_tag_content',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='idx_tag_name',
        ),
        migrations.RemoveField(
            model_name='knowledgepoint',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='knowledgepoint',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='knowledgepoint',
            name='name',
            field=models.CharField(help_text='如: 循环结构', max_length=100, verbose_name='知识点名称'),
        ),
        migrations.AlterField(
            model_name='knowledgepoint',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='knowledge.knowledgepoint', verbose_name='父知识点'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='标签名称'),
        ),
        migrations.AddField(
            model_name='knowledgepointrelation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='knowledgepointrelation',
            name='knowledge_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_objects', to='knowledge.knowledgepoint', verbose_name='知识点'),
        ),
        migrations.AddField(
            model_name='tagrelation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_rels', to='knowledge.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgepointrelation',
            unique_together={('knowledge_point', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tagrelation',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
    ]
