# Generated by Django 5.1.6 on 2026-02-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseterm_status'),
        ('knowledge', '0002_knowledgepointrelation_tagrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoint',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_points', to='courses.course', verbose_name='所属课程'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='courses.course', verbose_name='所属课程'),
            preserve_default=False,
        ),
    ]
