# Generated by Django 5.1.6 on 2026-02-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseterm_status'),
        ('knowledge', '0003_knowledgepoint_course_tag_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件夹名称')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_categories', to='courses.course', verbose_name='所属课程')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.questioncategory', verbose_name='父文件夹')),
            ],
            options={
                'verbose_name': '题目分类',
                'verbose_name_plural': '题目分类',
                'db_table': 'question_categories',
                'ordering': ['order', 'id'],
            },
        ),
    ]
