# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如 计算机1班', max_length=100, verbose_name='班级名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '教学班级',
                'verbose_name_plural': '教学班级',
                'db_table': 'class_groups',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='courses/covers/%Y/%m/', verbose_name='课程封面')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='0.00代表免费', max_digits=10, verbose_name='价格')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=20, verbose_name='难度')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('published', '已发布'), ('rejected', '已拒绝')], default='draft', max_length=20, verbose_name='课程状态')),
                ('audit_remark', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('enrollment_count', models.IntegerField(default=0, verbose_name='报名人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如 后端开发, Python', max_length=50, verbose_name='分类名称')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序权重')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'db_table': 'course_categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如 2023秋季一期', max_length=100, verbose_name='班期名称')),
                ('start_date', models.DateField(verbose_name='开课日期')),
                ('end_date', models.DateField(verbose_name='结课日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='班期简介')),
                ('enrollment_limit', models.IntegerField(default=0, help_text='0表示不限制', verbose_name='招生人数限制')),
                ('status', models.CharField(choices=[('recruiting', '招生中'), ('in_progress', '进行中'), ('finished', '已结课')], default='recruiting', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程班期',
                'verbose_name_plural': '课程班期',
                'db_table': 'course_terms',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课时标题')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课时',
                'verbose_name_plural': '课时',
                'db_table': 'lessons',
                'ordering': ['chapter', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', '视频'), ('rich_text', '富文本'), ('file', '文件附件'), ('image', '图片'), ('code', '代码片段')], max_length=20, verbose_name='内容类型')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='块标题')),
                ('content', models.JSONField(blank=True, help_text='JSON存储配置/文本/代码片段', null=True, verbose_name='内容数据')),
                ('file', models.FileField(blank=True, help_text='视频/图片/附件', null=True, upload_to='lessons/files/%Y/%m/', verbose_name='文件资源')),
                ('order', models.IntegerField(default=0, verbose_name='块内排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课时内容块',
                'verbose_name_plural': '课时内容块',
                'db_table': 'lesson_content_blocks',
                'ordering': ['lesson', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, help_text='支持多级子章节', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.chapter', verbose_name='父章节')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'chapters',
                'ordering': ['course', 'order', 'id'],
            },
        ),
    ]
