# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='head_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='班主任/助教'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL, verbose_name='班级学生'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(help_text='防止误删教师导致课程孤立', on_delete=django.db.models.deletion.PROTECT, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='授课教师'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='所属课程'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.coursecategory', verbose_name='父分类'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory', verbose_name='课程分类'),
        ),
        migrations.AddField(
            model_name='courseterm',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='courses.course', verbose_name='关联课程'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='courses.courseterm', verbose_name='关联班期'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter', verbose_name='所属章节'),
        ),
        migrations.AddField(
            model_name='lessoncontentblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='courses.lesson', verbose_name='所属课时'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['course', 'order'], name='idx_chapter_order'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher'], name='idx_course_teacher'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='idx_course_category'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='idx_course_status'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='idx_course_created'),
        ),
        migrations.AddIndex(
            model_name='courseterm',
            index=models.Index(fields=['course', 'status'], name='idx_term_status'),
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('term', 'name')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['chapter', 'order'], name='idx_lesson_order'),
        ),
    ]
