# Generated by Django 5.1.6 on 2026-02-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='is_visible',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.coursecategory', verbose_name='课程分类'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='courses.coursecategory', verbose_name='父分类'),
        ),
    ]
