# Generated by Django 5.1.6 on 2026-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_coursecategory_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseterm',
            name='status',
            field=models.CharField(choices=[('in_progress', '进行中'), ('finished', '已结课')], default='recruiting', max_length=20, verbose_name='状态'),
        ),
    ]
