# Generated by Django 5.1.6 on 2026-02-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseterm_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseterm',
            name='enrollment_limit',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='class_limit',
            field=models.IntegerField(default=0, help_text='0表示不限制', verbose_name='班级人数限制'),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='班期简介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('finished', '已结课')], default='not_started', max_length=20, verbose_name='状态'),
        ),
    ]
