# Generated by Django 5.1.6 on 2026-02-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(help_text='如 ORD20231027001', max_length=50, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('snapshot_price', models.DecimalField(decimal_places=2, help_text='下单时的单价，防止后续改价', max_digits=10, verbose_name='价格快照')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('payment_method', models.CharField(blank=True, choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('system_free', '系统免费')], max_length=20, null=True, verbose_name='支付方式')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='第三方支付流水号')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='退款金额')),
                ('refund_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='退款原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('term', models.ForeignKey(help_text='购买的是具体班期', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='courses.courseterm', verbose_name='关联班期')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'finance_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
