# Generated by Django 5.1.6 on 2025-04-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiankong_Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answer', models.TextField(max_length=200, verbose_name='正确答案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('judgment', '判断题'), ('fill_in_the_blank', '填空题'), ('short_answer', '简答题')], max_length=20, verbose_name='题型')),
                ('content', models.TextField(help_text='支持HTML/Markdown格式', verbose_name='题目内容')),
                ('choice_options', models.JSONField(blank=True, default=list, null=True, verbose_name='选择题选项')),
                ('explanation', models.TextField(blank=True, help_text='额外说明')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.node', verbose_name='所属节点')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='JudgmentAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answer', models.JSONField(blank=True, default=list, null=True, verbose_name='正确答案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judgment_answer', to='quiz.question')),
            ],
            options={
                'verbose_name': '判断题答案',
                'verbose_name_plural': '判断题答案',
            },
        ),
        migrations.CreateModel(
            name='Jianda_Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jianda_answer', to='quiz.question')),
            ],
            options={
                'verbose_name': '简答题',
                'verbose_name_plural': '简答题',
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answer', models.JSONField(blank=True, default=list, null=True, verbose_name='正确答案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answer', to='quiz.question')),
            ],
            options={
                'verbose_name': '选择题答案',
                'verbose_name_plural': '选择题答案',
            },
        ),
        migrations.CreateModel(
            name='Question_Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, null=True, verbose_name='回答内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
            },
        ),
    ]
