# Generated by Django 5.1.6 on 2025-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jianda_answer',
            options={'verbose_name': '简答题答案', 'verbose_name_plural': '简答题答案'},
        ),
        migrations.AlterModelOptions(
            name='tiankong_answer',
            options={'verbose_name': '填空题答案', 'verbose_name_plural': '填空题答案'},
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='correct_answer',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='jianda_answer',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='正确答案', max_length=200, null=True, verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='judgmentanswer',
            name='correct_answer',
            field=models.BooleanField(blank=True, help_text='正确答案', null=True, verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_options',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='选择题选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='额外说明', null=True),
        ),
        migrations.AlterField(
            model_name='question_submission',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='是否正确', null=True, verbose_name='是否正确'),
        ),
        migrations.AlterField(
            model_name='question_submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='提交时间', verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='tiankong_answer',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='正确答案', max_length=200, null=True, verbose_name='正确答案'),
        ),
    ]
