# Generated by Django 5.1.6 on 2026-02-06 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system', '系统消息'), ('course', '课程消息'), ('interaction', '互动消息'), ('security', '安全消息')], default='system', max_length=20, verbose_name='消息类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('related_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'db_table': 'system_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='如 site_name, allow_register', max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(help_text='支持各种类型', verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('is_public', models.BooleanField(default=False, help_text='前端可见', verbose_name='是否公开')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_configs',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, help_text='Celery Task ID', unique=True, verbose_name='任务ID')),
                ('name', models.CharField(help_text='如 generate_exam, transcode_video', max_length=100, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failure', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('result', models.JSONField(blank=True, help_text='如 生成的试卷ID, 错误信息', null=True, verbose_name='任务结果')),
                ('progress', models.IntegerField(default=0, help_text='0-100', verbose_name='进度')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '异步任务',
                'verbose_name_plural': '异步任务',
                'db_table': 'system_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
