# Generated by Django 5.1.6 on 2026-02-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_accepted', models.BooleanField(default=False, help_text='作为最佳答案', verbose_name='是否采纳')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'community_comments',
                'ordering': ['-is_accepted', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞',
                'db_table': 'community_comment_likes',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
            ],
            options={
                'verbose_name': '帖子点赞',
                'verbose_name_plural': '帖子点赞',
                'db_table': 'community_post_likes',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='如 技术分享, 公共问答', max_length=50, null=True, verbose_name='分类')),
                ('title', models.CharField(max_length=200, verbose_name='帖子标题')),
                ('excerpt', models.CharField(blank=True, help_text='列表页显示', max_length=500, null=True, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('type', models.CharField(choices=[('question', '问答'), ('discussion', '讨论')], default='discussion', max_length=20, verbose_name='类型')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_essence', models.BooleanField(default=False, verbose_name='是否加精')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('reply_count', models.IntegerField(default=0, help_text='冗余字段，优化查询', verbose_name='回复数')),
                ('like_count', models.IntegerField(default=0, help_text='冗余字段', verbose_name='点赞数')),
                ('last_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='最后回复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'community_threads',
                'ordering': ['-is_pinned', '-last_reply_at', '-created_at'],
            },
        ),
    ]
